---
driver_plugin: openstack

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
driver_config:
  openstack_username: vagrant
  openstack_api_key: vagrant
  openstack_auth_url: http://172.21.42.2:5000/v2.0/tokens
  require_chef_omnibus: latest
  image_ref: Ubuntu Server 12.04
  flavor_ref: mx.medium
  floating_ip_pool: nova
  key_name: eindbaas-key
  private_key_path: /home/klm21904/.ssh/eindbaas-key
  username: ubuntu
  server_name: bamboo-dev
  disable_ssl_validation: true

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[bamboo]
    attributes:
      bamboo:
        name: bamboo-dev
      apt:
        compiletime: true
